Repository toantranmei/mei-nuxt3-ui, pull requests merged in 2024-04, with the labels that each got.

#2 fix(components): fix undefined from colors of tailwindcss
  playground/app.vue
Labels: bug

#5 feat(components): add atom component modal
  playground/pages/button.vue
  playground/pages/modal.vue
  src/runtime/components/atoms/button.vue
  src/runtime/components/atoms/modal.vue
  src/runtime/ui-configs/index.ts
  src/runtime/ui-configs/modal.ts
Labels: enhancement

#8 feat(components): make card atom component ui
  playground/pages/card.vue
  src/runtime/components/atoms/card.vue
  src/runtime/ui-configs/card.ts
  src/runtime/ui-configs/index.ts
Labels: enhancement

#11 feat(components): make alert atom component ui
  playground/pages/alert.vue
  src/runtime/components/atoms/alert.vue
  src/runtime/types/alert.ts
  src/runtime/types/index.ts
  src/runtime/ui-configs/alert.ts
  src/runtime/ui-configs/index.ts
Labels: enhancement, help wanted
